### ISSUE TITLE
Using on Alienware 15 R2

### ISSUE THREAD

**Issue by AienTech** [erlkonig/alienfx#2]
Hi, thanks for providing this scripts.
I'm currently using Alienware 15 R2, is there any way that I could use this scripts on my laptop?

if so, please provide me some guides.

Many thanks

**Comment by erlkonig** [comment]
Hi AlenTech.  I'd like to help, but I don't have an Alienware laptop.  The alienfx-uptime is a bash script, so you'd want to compile and test the underlying alienfx program first and see what happens before doing anything with alienfx-uptime.

**Comment by erlkonig** [comment]
I should mention that I started figuring my lighting out by just trying different values for things (which admittedly took code changes in some cases).  If you *do* figure out what values are needed, submit a pull request or tell me what you find.

I'm going to close this issue, since there isn't a way forward until someone provides Alienware 15 R2 info.
